name: Build OpenAPI and commit changes

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: "openapi/einnsyn.openapi.yml"
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            export SHA=$( git rev-parse :$FILE_TO_COMMIT )
            export BRANCH=$( git rev-parse --abbrev-ref HEAD )
            gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
              --field message="Autogenerate OpenAPI spec from TypeSpec" \
              --field content=@<( base64 -i $FILE_TO_COMMIT ) \
              --field branch="$BRANCH" \
              --field sha="$SHA"
          fi
