name: Build OpenAPI and commit changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'typespec/**'

permissions:
  contents: read

jobs:
  build-and-commit:
    if: ${{ github.actor != 'einnsyn-codegen[bot]' }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Fetch app token
        uses: actions/create-github-app-token@v3.2.0 # This release is immutable, so pinning to a commit is not necessary
        id: gh-api-token
        with:
          app-id: ${{ secrets.EIN_CODEGEN_APP_ID }}
          private-key: ${{ secrets.EIN_CODEGEN_APP_PRIVATE_KEY }}
          
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          ref: ${{ github.head_ref }}
          
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # pin@v2.2.0
        with:
          bun-version: 1.4.2
      - run: bun install
      - run: bun run build
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ steps.gh-api-token.outputs.token }}
          FILE_TO_COMMIT: "openapi/einnsyn.openapi.yml"
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            export BRANCH=${{ github.head_ref }}
            export SHA=$( git rev-parse "$BRANCH:$FILE_TO_COMMIT" )
            echo "Branch: $BRANCH"
            echo "SHA: $SHA"
            git branch --list
            gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
              --field message="Autogenerate OpenAPI spec from TypeSpec" \
              --field content=@<( base64 -i $FILE_TO_COMMIT ) \
              --field branch="$BRANCH" \
              --field sha="$SHA"
          fi
